# Generated by Django 3.1.3 on 2020-11-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_auto_20201109_0311"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
    ]
